name: test

env:
  TURBO_API: "https://cache.turbocache.build"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "team_turbocache_action"
  TURBO_RUN_SUMMARY: true

on:
  push:
    branches:
      - main
      - "releases/*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn

      - run: yarn turbo lint build test
      - run: yarn package

      # Run self
      - uses: ./
